baseURL = 'http://flofricke.github.io/sv-tyrol-abbensen/'
defaultContentLanguage = 'de'
title = 'Schützenverein Tyrol-Abbensen'
theme = 'highway'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Neuigkeiten"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "verein"
    name = "Der Verein"
    url = "/verein/"
    weight = 2
  [[menu.main]]
    identifier = "vorstand"
    name = "Der Vorstand"
    url = "/verein/vorstand/"
    parent = "verein"
    weight = 1
  [[menu.main]]
    identifier = "vorsitzende"
    name = "Chronik der Vorsitzenden"
    url = "/verein/vorsitzende/"
    parent = "verein"
    weight = 2
  [[menu.main]]
    identifier = "sportschiessen"
    name = "Sportliches Schießen"
    url = "/verein/sportschiessen/"
    parent = "verein"
    weight = 3    

    
[Params]
  mainSections = ["neuigkeiten"]
  logo = "img/Wappen_Abbensen.jpg"
  subtitle = "Seit 1901" # Logo subtitle
  readmore = true # Show "Read more" button in list if true

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

